project:
  type: website
  output-dir: docs

website:
  title: "Eda Ozkaya"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts/index.qmd
        text: Blog
      
    collections:
      blog:
        type: [posts]
        path: blog
        sort: date

format:
  html:
    theme: journal
    css: custom.css
    toc: true



